version: '3.8'

services:
  front:
    build:
      context: .
      dockerfile: front/Dockerfile
    ports:
      - "80:80"
    depends_on:
      - server
    networks:
      - app-network

  server:
    build:
      context: .
      dockerfile: server/Dockerfile
    ports:
      - "8088:8088"
    environment:
      - NODE_ENV=production
    networks:
      - app-network

networks:
  app-network:
    driver: bridge